#ifndef DASHBOARD_H
#define DASHBOARD_H

const char index_html[] PROGMEM = R"rawliteral(
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>ESP32BusDash</title><style>
:root{color-scheme:dark}body{margin:0;background:#070b12;color:#eaf2ff;font:16px system-ui;text-align:center}.top{position:sticky;top:0;background:#0e1623;padding:8px;border-bottom:1px solid #24364e;display:flex;justify-content:space-between}.menu{max-width:720px;margin:14px auto;padding:10px;background:#101b2a;border-radius:9px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:9px;max-width:720px;margin:auto;padding:0 10px}.card{background:#101b2a;border:1px solid #24364e;border-radius:9px;padding:10px}.n{font-size:2rem;color:#32e6bf;font-weight:700}.u{font-size:.7rem;color:#91a2b9}button{padding:9px 12px;border:0;border-radius:6px;background:#1d8c73;color:white;font-weight:700}button.on{background:#b23b3b}.bad{color:#ff8f8f}.ok{color:#68e09a}a{color:#7bbcff}
</style></head><body><div class="top"><b>ESP32BusDash</b><span id="status">Connecting</span></div>
<div class="menu"><button id="capture" onclick="toggleCapture()">Start all-packet capture</button> <a href="/diagnostics.csv">Download DTC log</a> <a href="/captures">List captures</a><div class="u">Capture is candump-compatible text on SD. It records every received CAN frame.</div></div>
<div class="grid"><div class="card"><div class="u">ENGINE RPM</div><div id="rpm" class="n">0</div></div><div class="card"><div class="u">SPEED MPH</div><div id="speed" class="n">0</div></div><div class="card"><div class="u">COOLANT F</div><div id="coolant" class="n">0</div></div><div class="card"><div class="u">OIL PSI</div><div id="oil" class="n">0</div></div><div class="card"><div class="u">PRIMARY AIR PSI</div><div id="air1" class="n">0</div></div><div class="card"><div class="u">SECONDARY AIR PSI</div><div id="air2" class="n">0</div></div><div class="card"><div class="u">BATTERY V</div><div id="volt" class="n">0.0</div></div><div class="card"><div class="u">FUEL LEVEL %</div><div id="fuel" class="n">0</div></div><div class="card"><div class="u">ODOMETER MI</div><div id="odo" class="n">0</div></div><div class="card"><div class="u">ACTIVE DTC</div><div id="dtc" class="n bad">None</div></div></div>
<div class="menu u">Packets: <span id="packets">0</span> | SD: <span id="sd">--</span> | Capture write failures: <span id="dropped">0</span></div>
<script>let ws,capture=false;function e(id,v){document.getElementById(id).textContent=v}function connect(){ws=new WebSocket(`ws://${location.host}/ws`);ws.onopen=()=>e('status','Connected');ws.onclose=()=>{e('status','Reconnecting');setTimeout(connect,1500)};ws.onmessage=x=>{let d=JSON.parse(x.data);for(let k of ['rpm','speed','coolant','oil','air1','air2','fuel','odo','packets','dropped'])e(k,d[k]);e('volt',Number(d.volt).toFixed(1));e('sd',d.sd?'READY':'MISSING');e('dtc',d.spn?`SPN ${d.spn} FMI ${d.fmi}`:'None');capture=d.capture;let b=document.getElementById('capture');b.textContent=capture?'Stop all-packet capture':'Start all-packet capture';b.className=capture?'on':''}}function toggleCapture(){fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'enabled='+(!capture)}).then(r=>{if(!r.ok)alert('SD card unavailable')})}connect()</script></body></html>
)rawliteral";
#endif
