[platformio]
src_dir = .
include_dir = include

[env:esp32-s3-cyd35]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
platform_packages =
  platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.3
  platformio/framework-arduinoespressif32-libs @ https://github.com/esp-arduino-libs/arduino-esp32-sdk.git#high_perf/v3.0.3
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_16MB.csv
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=3
  -D LV_CONF_INCLUDE_SIMPLE
lib_deps =
  ESP32Async/ESPAsyncWebServer @ ^3.6.0
  ESP32Async/AsyncTCP @ ^3.3.2
  bblanchon/ArduinoJson @ ^7.2.1
  https://github.com/esp-arduino-libs/esp-lib-utils.git
  https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
  https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
  lvgl/lvgl @ 8.3.11
